<?php

namespace NachoBrito\ThoughtsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThoughtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThoughtRepository extends EntityRepository
{
}
